import { BEOrder } from '@src/@types/Menu'
import { nanoid } from 'nanoid'

export const FakeOrders: BEOrder[] = [
	{
		id: nanoid(4),
		paidWith: 'card',
		createdAt: '10/07/01',
		subtotal: 26.89,
		tax: 12,
		total: 14.89,
		products: [
			{
				name: 'small pizza',
				description: '8 inch pizza',
				price: 10.99,
				categoryId: nanoid(4),
				id: nanoid(4),
				createdAt: '10/07/01',
				updatedAt: '10/07/01',
				topping: [
					{
						createdAt: '10/07/01',
						updatedAt: '10/07/01',
						id: nanoid(4),
						name: 'olives',
						priceSmall: 1.5,
					},
				],
			},
			{
				name: 'pazookie',
				description: 'cookie baked in a pan',
				price: 4.99,
				categoryId: nanoid(4),
				id: nanoid(4),
				createdAt: '10/07/01',
				updatedAt: '10/07/01',
				topping: [],
			},
		],
	},
	{
		id: nanoid(4),
		paidWith: 'card',
		subtotal: 26.89,
		tax: 12,
		total: 14.89,
		createdAt: '10/07/01',
		products: [
			{
				name: 'large pizza',
				description: '12 inch pizza',
				price: 12.99,
				categoryId: nanoid(4),
				id: nanoid(4),
				createdAt: '10/07/01',
				updatedAt: '10/07/01',
				topping: [
					{
						createdAt: '10/07/01',
						updatedAt: '10/07/01',
						id: nanoid(4),
						name: 'olives',
						priceSmall: 1.5,
					},
				],
			},
			{
				name: 'salad',
				description: 'good ol salad',
				price: 4.99,
				categoryId: nanoid(4),
				id: nanoid(4),
				createdAt: '10/07/01',
				updatedAt: '10/07/01',
				topping: [],
			},
		],
	},
	{
		id: nanoid(4),
		paidWith: 'card',
		subtotal: 26.89,
		tax: 12,
		total: 14.89,
		createdAt: '10/07/01',
		products: [
			{
				name: 'small pizza',
				description: '8 inch pizza',
				price: 10.99,
				categoryId: nanoid(4),
				id: nanoid(4),
				createdAt: '10/07/01',
				updatedAt: '10/07/01',
				topping: [
					{
						createdAt: '10/07/01',
						updatedAt: '10/07/01',
						id: nanoid(4),
						name: 'olives',
						priceSmall: 1.5,
					},
				],
			},
			{
				name: 'pazookie',
				description: 'cookie baked in a pan',
				price: 4.99,
				categoryId: nanoid(4),
				id: nanoid(4),
				createdAt: '10/07/01',
				updatedAt: '10/07/01',
				topping: [],
			},
		],
	},
	{
		id: nanoid(4),
		paidWith: 'card',
		subtotal: 26.89,
		tax: 12,
		total: 14.89,
		createdAt: '10/07/01',
		products: [
			{
				name: 'large pizza',
				description: '12 inch pizza',
				price: 12.99,
				categoryId: nanoid(4),
				id: nanoid(4),
				createdAt: '10/07/01',
				updatedAt: '10/07/01',
				topping: [
					{
						createdAt: '10/07/01',
						updatedAt: '10/07/01',
						id: nanoid(4),
						name: 'olives',
						priceSmall: 1.5,
					},
				],
			},
			{
				name: 'salad',
				description: 'good ol salad',
				price: 4.99,
				categoryId: nanoid(4),
				id: nanoid(4),
				createdAt: '10/07/01',
				updatedAt: '10/07/01',
				topping: [],
			},
		],
	},
]
